/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import com.mysql.cj.xdevapi.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Font;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP ProBook
 */
public class orders extends javax.swing.JFrame {

    /**
     * Creates new form orders
     */
    public orders() {
        initComponents();
        transactID.setVisible(false);
        displayBreakfast();
        displayLunch();
        displayDinner();
        displayTransaction();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        neworderButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        breakfastTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lunchTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dinnerTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        confirmBillButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        transactTable = new javax.swing.JTable();
        transactID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logoutButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        products = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        transactions = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        orders = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        accounts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setForeground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 58, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Menu ID");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 93, 35));
        jPanel7.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 192, 35));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Quantity");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 93, 35));
        jPanel7.add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 192, 35));

        neworderButton.setBackground(new java.awt.Color(44, 97, 93));
        neworderButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        neworderButton.setText("Order");
        neworderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neworderButtonActionPerformed(evt);
            }
        });
        jPanel7.add(neworderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 180, 44));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Price");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 93, 35));
        jPanel7.add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 192, 35));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Menu Name");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 93, 35));
        jPanel7.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 192, 35));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 532, 455));

        jPanel2.setLayout(null);
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 64, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        breakfastTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        breakfastTable.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        breakfastTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu ID", "Menu Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        breakfastTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breakfastTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(breakfastTable);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 180));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("BREAKFAST");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 4, 130, 30));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 230));

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lunchTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lunchTable.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lunchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu ID", "Menu Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lunchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lunchTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lunchTable);

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 180));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("LUNCH");
        jPanel12.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 130, 30));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 320, 230));

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dinnerTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dinnerTable.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dinnerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu ID", "Menu Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dinnerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dinnerTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(dinnerTable);

        jPanel13.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 180));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("DINNER");
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 4, 130, 30));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 300, 230));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, -1, -1));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, -1, 100));

        jSeparator6.setBackground(new java.awt.Color(102, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(102, 255, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, 450));

        jSeparator2.setForeground(new java.awt.Color(102, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 242, 970, 10));

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmBillButton.setBackground(new java.awt.Color(44, 97, 93));
        confirmBillButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        confirmBillButton.setText("Confirm Bill");
        confirmBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBillButtonActionPerformed(evt);
            }
        });
        jPanel14.add(confirmBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 180, 44));

        transactTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transac ID", "Item ", "Quantity", "Sub-total"
            }
        ));
        transactTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(transactTable);

        jPanel14.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 320, 210));
        jPanel14.add(transactID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, -1));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 265, 350, 460));

        jPanel1.setBackground(new java.awt.Color(44, 97, 93));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cuisina");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(29, 11, 141, 33);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 55, 170, 10);

        logoutButton.setBackground(new java.awt.Color(0, 102, 102));
        logoutButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(30, 540, 131, 37);

        dashboard.setBackground(new java.awt.Color(44, 97, 93));
        dashboard.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setText("Dashboard");
        dashboard.setOpaque(true);
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 120, 170, 50);

        products.setBackground(new java.awt.Color(44, 97, 93));
        products.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        products.setForeground(new java.awt.Color(255, 255, 255));
        products.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        products.setText("Products");
        products.setOpaque(true);
        products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(products, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(products, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 190, 170, 50);

        transactions.setBackground(new java.awt.Color(44, 97, 93));
        transactions.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        transactions.setForeground(new java.awt.Color(255, 255, 255));
        transactions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactions.setText("Transactions");
        transactions.setOpaque(true);
        transactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactionsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transactions, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transactions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 270, 170, 50);

        orders.setBackground(new java.awt.Color(44, 97, 93));
        orders.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        orders.setForeground(new java.awt.Color(255, 255, 255));
        orders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orders.setText("Orders");
        orders.setOpaque(true);
        orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordersMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10);
        jPanel10.setBounds(0, 340, 170, 50);

        accounts.setBackground(new java.awt.Color(44, 97, 93));
        accounts.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        accounts.setForeground(new java.awt.Color(255, 255, 255));
        accounts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accounts.setText("Accounts");
        accounts.setOpaque(true);
        accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accounts, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accounts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11);
        jPanel11.setBounds(0, 420, 170, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(594, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 704, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void neworderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neworderButtonActionPerformed
        float price = Float.parseFloat(priceTextField.getText());
        int quantity = Integer.parseInt(quantityTextField.getText());
        try {
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/system_pos", "root", "");
            java.sql.Statement stmt = conn.createStatement();

            String query = String.format("INSERT INTO transactions(menu_id,menu_name, bill, quantity,status) VALUES ('%s','%s','%f',%d,0) ", idTextField.getText(),nameTextField.getText(), price * quantity, Integer.parseInt(quantityTextField.getText()));
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "You have successfully order");
            displayTransaction();
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_neworderButtonActionPerformed

    private void breakfastTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breakfastTableMouseClicked
         DefaultTableModel model = (DefaultTableModel) breakfastTable.getModel();
        int selectedRowIndex = breakfastTable.getSelectedRow();

        idTextField.setText(model.getValueAt(selectedRowIndex, 0).toString());
        nameTextField.setText(model.getValueAt(selectedRowIndex, 1).toString());
        priceTextField.setText(model.getValueAt(selectedRowIndex, 2).toString());
        quantityTextField.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_breakfastTableMouseClicked

    private void lunchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lunchTableMouseClicked
         DefaultTableModel model = (DefaultTableModel) lunchTable.getModel();
        int selectedRowIndex = lunchTable.getSelectedRow();

        idTextField.setText(model.getValueAt(selectedRowIndex, 0).toString());
        nameTextField.setText(model.getValueAt(selectedRowIndex, 1).toString());
        priceTextField.setText(model.getValueAt(selectedRowIndex, 2).toString());
        quantityTextField.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_lunchTableMouseClicked

    private void dinnerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dinnerTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) dinnerTable.getModel();
        int selectedRowIndex = dinnerTable.getSelectedRow();

        idTextField.setText(model.getValueAt(selectedRowIndex, 0).toString());
        nameTextField.setText(model.getValueAt(selectedRowIndex, 1).toString());
        priceTextField.setText(model.getValueAt(selectedRowIndex, 2).toString());
        quantityTextField.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_dinnerTableMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        new dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        dashboard.setForeground(Color.pink);
        dashboard.setFont(new Font("Tahoma", Font.BOLD, 18));
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        dashboard.setForeground(Color.white);
        dashboard.setFont(new Font("Verdana", Font.BOLD, 12));
    }//GEN-LAST:event_dashboardMouseExited

    private void productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseClicked

    }//GEN-LAST:event_productsMouseClicked

    private void productsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseEntered
        products.setForeground(Color.pink);
        products.setFont(new Font("Tahoma", Font.BOLD, 18));
    }//GEN-LAST:event_productsMouseEntered

    private void productsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseExited
        products.setForeground(Color.white);
        products.setFont(new Font("Verdana", Font.BOLD, 12));
    }//GEN-LAST:event_productsMouseExited

    private void transactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionsMouseClicked
        new transactions().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionsMouseClicked

    private void transactionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionsMouseEntered
        transactions.setForeground(Color.pink);
        transactions.setFont(new Font("Tahoma", Font.BOLD, 18));
    }//GEN-LAST:event_transactionsMouseEntered

    private void transactionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionsMouseExited
        transactions.setForeground(Color.white);
        transactions.setFont(new Font("Verdana", Font.BOLD, 12));
    }//GEN-LAST:event_transactionsMouseExited

    private void ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseClicked
        new orders().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ordersMouseClicked

    private void ordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseEntered
        orders.setForeground(Color.pink);
        orders.setFont(new Font("Tahoma", Font.BOLD, 18));
    }//GEN-LAST:event_ordersMouseEntered

    private void ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseExited
        orders.setForeground(Color.white);
        orders.setFont(new Font("Verdana", Font.BOLD, 12));
    }//GEN-LAST:event_ordersMouseExited

    private void accountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseEntered
        accounts.setForeground(Color.pink);
        accounts.setFont(new Font("Tahoma", Font.BOLD, 18));
    }//GEN-LAST:event_accountsMouseEntered

    private void accountsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseExited
        accounts.setForeground(Color.white);
        accounts.setFont(new Font("Verdana", Font.BOLD, 12));
    }//GEN-LAST:event_accountsMouseExited

    private void accountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseClicked
       new accounts().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_accountsMouseClicked

    private void confirmBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBillButtonActionPerformed
      try {
            Class.forName("com.mysql.jdbc.Driver");//load the driver
            try ( java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/system_pos", "root", ""))//establishes connection
            {
                java.sql.Statement stmt = (java.sql.Statement) con.createStatement(); //get the connection stream(connection port)
                stmt.executeUpdate(String.format("UPDATE transactions SET status = 1 WHERE order_id = %d",Integer.parseInt(transactID.getText())));
                JOptionPane.showMessageDialog(this, "Order Paid");
                con.close();
                displayTransaction();
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        };
    }//GEN-LAST:event_confirmBillButtonActionPerformed

    private void transactTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) transactTable.getModel();
        int selectedRowIndex = transactTable.getSelectedRow();
        
        transactID.setText(model.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_transactTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orders().setVisible(true);
            }
        });
    }
    
    public void displayBreakfast() {
        int ctr = 0;
        breakfastTable.setModel(new DefaultTableModel(null, new String[]{"Menu Id", "Menu Name","Price"}));
        try {
            Class.forName("com.mysql.jdbc.Driver");//load the driver
            try ( java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/system_pos", "root", ""))//establishes connection
            {
                java.sql.Statement stmt = (java.sql.Statement) con.createStatement(); //get the connection stream(connection port)
                ResultSet datas = stmt.executeQuery("SELECT * FROM menu WHERE menu_type = 'breakfast' and availability='available'");
                DefaultTableModel model = (DefaultTableModel) breakfastTable.getModel();
//                    System.out.println(datas.getString("m"));
                while (datas.next()) {
                    
                    ctr = 1;
                    model.addRow(new Object[]{datas.getInt("menu_id"), datas.getString("menu_name"), datas.getFloat("price")
                       });
                }
                
                if (ctr == 0) {
                    JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);
                }
                con.close();
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        };
    }
    public void displayLunch(){
    
     int ctr = 0;
        lunchTable.setModel(new DefaultTableModel(null, new String[]{"Menu Id", "Menu Name","Price"}));
        try {
            Class.forName("com.mysql.jdbc.Driver");//load the driver
            try ( java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/system_pos", "root", ""))//establishes connection
            {
                java.sql.Statement stmt = (java.sql.Statement) con.createStatement(); //get the connection stream(connection port)
                ResultSet datas = stmt.executeQuery("SELECT * FROM menu WHERE menu_type = 'lunch' and availability='available'");
                DefaultTableModel model = (DefaultTableModel) lunchTable.getModel();
//                    System.out.println(datas.getString("m"));
                while (datas.next()) {
                    
                    ctr = 1;
                    model.addRow(new Object[]{datas.getInt("menu_id"), datas.getString("menu_name"), datas.getFloat("price")
                       });
                }
                
                if (ctr == 0) {
                    JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);
                }
                con.close();
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        };
    }
    public void displayDinner(){
     int ctr = 0;
        dinnerTable.setModel(new DefaultTableModel(null, new String[]{"Menu Id", "Menu Name","Price"}));
        try {
            Class.forName("com.mysql.jdbc.Driver");//load the driver
            try ( java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/system_pos", "root", ""))//establishes connection
            {
                java.sql.Statement stmt = (java.sql.Statement) con.createStatement(); //get the connection stream(connection port)
                ResultSet datas = stmt.executeQuery("SELECT * FROM menu WHERE menu_type = 'dinner' and availability='available'");
                DefaultTableModel model = (DefaultTableModel) dinnerTable.getModel();
//                    System.out.println(datas.getString("m"));
                while (datas.next()) {
                    
                    ctr = 1;
                    model.addRow(new Object[]{datas.getInt("menu_id"), datas.getString("menu_name"), datas.getFloat("price")
                       });
                }
                
                if (ctr == 0) {
                    JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);
                }
                con.close();
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        };
    }
    
    public void displayTransaction(){
        transactTable.setModel(new DefaultTableModel(null, new String[]{"Transac ID", "Item","Quantity","Sub-total"}));
        try {
            Class.forName("com.mysql.jdbc.Driver");//load the driver
            try ( java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/system_pos", "root", ""))//establishes connection
            {
                java.sql.Statement stmt = (java.sql.Statement) con.createStatement(); //get the connection stream(connection port)
                ResultSet datas = stmt.executeQuery("SELECT * FROM transactions WHERE status = 0");
                DefaultTableModel model = (DefaultTableModel) transactTable.getModel();
                while(datas.next()){
                    model.addRow(new Object[]{datas.getInt("order_id"), datas.getString("menu_name"), datas.getInt("quantity"), datas.getFloat("bill")});
                }
                con.close();
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accounts;
    private javax.swing.JTable breakfastTable;
    private javax.swing.JButton confirmBillButton;
    private javax.swing.JLabel dashboard;
    private javax.swing.JTable dinnerTable;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTable lunchTable;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton neworderButton;
    private javax.swing.JLabel orders;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel products;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTextField transactID;
    private javax.swing.JTable transactTable;
    private javax.swing.JLabel transactions;
    // End of variables declaration//GEN-END:variables
}
